### ISSUE TITLE
NetSprocket support

### ISSUE THREAD

**Issue by carrotcreamsoup** [jorio/Pomme#6]
I was wondering if there was any plan to implement NetSprockets into Pomme? This would give the ability to support multiplayer Cro-Mag Rally, for example.

I have started an implementation of NetSprockets on my side to be able to race with family members in Europe (whom are as nostalgic as I am), but I am aware you may also be working on NetSprockets, which is why I am opening this issue.

Thanks!

**Comment by jorio** [comment]
Yup, I have begun implementing net play in CMR, but I'm taking a different path: CMR is probably the only NetSprocket title I'll ever port, so I'm writing the low-level net plumbing in the game itself rather than Pomme.

This should allow more flexibility down the line. The original netcode assumes reliable packet delivery over a LAN, and I have my doubts as to how it'll fare over the internet. So, since the netcode is likely to need heavy refactoring later, I'm not keen on maintaining source compat with NetSprocket.

I'm out of town this week, but I can push a WIP branch when I get back if you're interested.

**Comment by carrotcreamsoup** [comment]
That's a totally good reason. Definitely interested in your WIP branch if ever you have the time to push!

**Comment by jorio** [comment]
Hi @fordcars, sorry this took me so long — I have pushed the updated net code in CMR. You may also be interested in the discussion at https://github.com/jorio/CroMagRally/issues/3
